# Output directory (can be relative or absolute)
#input_directory: "/u/project/ngarud/Garud_lab/hsiao_data/fastqs_renamed"
#output_directory: "/u/project/ngarud/Garud_lab/averster/mag_results/"
#input_directory: "/u/scratch/a/averster/honduras/sra/"
input_directory: "/u/scratch/a/averster/honduras_sra/"
output_directory: "/u/scratch/a/averster/honduras/mag_smk"

skip_qc: False
scratch_dir: null # Put a patch in here to use a scratch directory for the QC section of the pipeline

samples_sub:

#- "SRR25572030"
#- "SRR25572031"
#- "SRR25572032"
#- "SRR25572033"
#- "SRR25572034"
#- "SRR25572035"
#- "SRR25572036"
#- "SRR25572037"
#- "SRR25572038"
#- "SRR25572039"



samples_ignore:
    - "SRR25571839"
    - "SRR25477917"
    - "SRR25571419"
    - "SRR25448135"
    - "SRR25477699"
    - "SRR25571697"
    - "SRR25571586"
    - "SRR25571471"
    - "SRR25571912"
    - "SRR25571832"
    - "SRR25571936"
    - "SRR25571922"
    - "SRR25448197"
    - "SRR25571944"
    - "SRR25571941"
    - "SRR25571947"
    - "SRR25571950"
    - "SRR25477870"

# Path to sample metadata CSV file
coassembly: False
sample_table: #"/u/project/ngarud/Garud_lab/hsiao_data/metadata.csv"
sample_col: #"sample_id" # It assumes you have files {sample}_1.fastq.gz and {sample}_2.fastq.gz
batch_col: #"batch_id" # Samples with the same batch_id are co-assembled

remove_host: False
host_genome: "/u/project/ngarud/Garud_lab/averster/mag_results/Sequences/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz"

# Checkm
checkm_data: "/u/project/ngarud/Garud_lab/MAG_assembly_databases/checkm_data"
checkm2_data: "/u/project/ngarud/averster/CheckM2_database/uniref100.KO.1.dmnd"

# Kraken
kraken2db: "/u/project/ngarud/Garud_lab/MAG_assembly_databases/kraken"
