executor: cluster-generic
cluster-generic-submit-cmd: "qsub -l h_vmem={resources.mem}G,h_rt={resources.time}:00:00 -pe shared {threads} -cwd -o logs_cluster/ -e logs_cluster/ -V"
cluster-generic-cancel-cmd: "qdel"
jobs: 10
rerun-incomplete: true
default-resources:
  - mem=4
  - time=2
  - threads=1
